name: Busted

on: [push, pull_request]

jobs:
  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.4", "5.3", "5.2", "5.1", "luajit", "luajit-openresty"]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v7
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v3
    - name: Setup dependencies
      run: |
        luarocks install --only-deps fluent-scm-0.rockspec
        luarocks install busted
        luarocks install dkjson
        luarocks install luafilesystem
        luarocks install lua-path
        luarocks install https://raw.githubusercontent.com/moteus/luacov-coveralls/master/rockspecs/luacov-coveralls-scm-0.rockspec
    - name: Run Busted Tests
      run: busted -c -v
    - name: Report Test Coverage
      if: success()
      continue-on-error: true
      run: luacov-coveralls -i fluent -e .luarocks
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
