name: Busted

on: [push, pull_request]

jobs:
  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.3", "5.2", "5.1", "luajit", "luajit-openresty"]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - name: Setup Lua Rocks
      uses: leafo/gh-actions-luarocks@v2
    - name: Setup dependencies
      run: |
        luarocks install --only-deps fluent-scm-0.rockspec
        luarocks install busted
        luarocks install luacov-coveralls
        luarocks install luafilesystem
        luarocks install dkjson
    - name: Run Busted Tests
      run: busted -c -v
    - name: Log coverage to coveralls.io
      if: matrix.luaVersion == '5.3' && success()
      continue-on-error: true
      run: luacov-coveralls -i fluent -e spec -v -t "${{ secrets.COVERALLS_TOKEN }}"
