name: Deploy

on:
  push:
    tags:
      - v*
    paths:
      - rockspecs/*.rockspec

jobs:

  affected:
    runs-on: ubuntu-20.04
    outputs:
      rockspecs: '["${{ steps.changed-files.outputs.all_modified_files }}"]'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: changed-files
      uses: tj-actions/changed-files@v18
      with:
        files: rockspecs/*.rockspec
        separator: '", "'

  build:
    needs: affected
    if: ${{ needs.affected.outputs.rockspecs }}
    strategy:
      fail-fast: false
      matrix:
        # Upstream Issue: https://github.com/leafo/gh-actions-luarocks/issues/8
        luaVersion: ["5.4", "5.3", "5.2", "5.1"] #, "luajit", "luajit-openresty"]
        # Upstream Issue: https://github.com/leafo/gh-actions-luarocks/issues/8
        luarocksVersion: ["3.1.3"] # , "2.4.2"]
        rockspec: ${{ fromJSON(needs.affected.outputs.rockspecs) }}
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4
      with:
        luarocksVersion: ${{ matrix.luarocksVersion }}
    - name: Confirm rockspec builds
      run: |
        luarocks --lua-version ${{ matrix.luaVersion }} --local build -- ${{ matrix.rockspec }}

  upload:
    needs: [affected, build]
    if: ${{ needs.affected.outputs.rockspecs && startsWith(github.ref, 'refs/tags/') && github.repository == 'alerque/fluent-lua' }}
    strategy:
      fail-fast: false
      matrix:
        rockspec: ${{ fromJSON(needs.affected.outputs.rockspecs) }}
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v9
    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup dependencies
      run: |
        luarocks install dkjson
    - run: |
        luarocks upload --force --api-key ${{ secrets.LUAROCKS_APIKEY }} -- ${{ matrix.rockspec }}
