name: Luacheck

on: [push, pull_request]

jobs:
  luacheck:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.3"]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - name: Setup Lua Rocks
      uses: leafo/gh-actions-luarocks@v2
    - name: Setup dependencies
      run: |
        luarocks install luacheck
    - name: Run Code Linter
      run: luacheck .
